### ISSUE TITLE
remix-form errors message localization

### ISSUE THREAD

**Issue by Mat-moran** [SeasonedSoftware/remix-forms#102]
Hi , 
How do you usually localize remix-form? I am stuck with it. 
There is no way to pass a variable to the zod schema if you want to export it right?

Thanks in advance

**Comment by diogob** [comment]
@Mat-moran if you are trying to translate the error messages from the parser it might be useful to take a look at [ZodErrorMap](
https://zod.dev/ERROR_HANDLING?id=customizing-errors-with-zoderrormap) documentation.

You could also use the `renderField` property (as in the [required indicator example](https://remix-forms.seasoned.cc/examples/render-field/required-indicator)) to customize the field labels and errors or even use the [form children function](https://remix-forms.seasoned.cc/examples/forms/form-with-children) for further flexibility.
