### ISSUE TITLE
Allow options of type `{ name?: string; value: string }[]`

### ISSUE THREAD

**Issue by gustavoguichard** [SeasonedSoftware/remix-forms#14]
As well as the labels, we could capitalize the values if no `name` is given ;)

**Comment by danielweinmann** [comment]
@diogob, this is not completed :) @gustavoguichard's goal here is to allow for nameless options, where we'd derive the name from the value.

**Comment by diogob** [comment]
@danielweinmann could you post some more details? I was talking to @gustavoguichard and we could come up with a good use case.
