### ISSUE TITLE
Did you have an example of multiple checkbox validator

### ISSUE THREAD

**Issue by nkrmr** [SeasonedSoftware/remix-forms#174]
Hello,

I want to make a multi-checkbox validator, but I don't find any solution within your project to do that.

![Screenshot 2023-03-28 at 14 36 24](https://user-images.githubusercontent.com/686395/228237935-75d94676-605a-4897-a29f-dc5238006f62.png)

I have a multi-checkbox and I want that the user selects at least one of them but I don't know how to do that with Zod and remix-form.

If you can help,

Best regards

**Comment by arjunyel** [comment]
This help? https://github.com/seasonedcc/remix-forms/issues/18#issuecomment-1140369343
