### ISSUE TITLE
Pass result into beforeSuccess callback along with request?

### ISSUE THREAD

**Issue by zkdiff** [SeasonedSoftware/remix-forms#22]
It would be nice if the result was passed in to this callback along with the request
https://github.com/SeasonedSoftware/remix-forms/blob/896ab6c5077918d19646f3f3c7017ac8f4c2b014/src/formAction.server.ts#L99

This would allow for something along the following lines:
```
export const action: ActionFunction = async ({ request }) =>
  formAction({
    request,
    schema,
    mutation,
    beforeSuccess: async ({ request, data }) => {
      const session = await getSession(request.headers.get("Cookie"));
      session.set("userId", data.userId);
      return redirect("/", {
        headers: { "Set-Cookie": await commitSession(session) },
      });
    },
  });
```

Would this be any better than just using performMutation directly? Seems like it might be a tiny bit nicer since by using beforeSuccess, the failure path doesn't need to be re-implemented.

```
export const action: ActionFunction = async ({ request }) => {
  const result = await performMutation({ request, schema, mutation });

  if (!result.success) {
    return json(result, 400);
  }

  const session = await getSession(request.headers.get("Cookie"));
  session.set("userId", result.data.userId);
  return redirect("/", {
    headers: { "Set-Cookie": await commitSession(session) },
  });
};
```

Edit: I think I do prefer to use performMutation directly for this case. I guess I am wondering what the ideal use-case for `beforeSuccess` would be but I'll go ahead and close this issue for now.

**Comment by gustavoguichard** [comment]
I'd also go for the performMutation option. I'm glad you were able to solve it!

**Comment by danielweinmann** [comment]
Hey, @zkdiff! Thanks for creating this issue :D 

I don't remember the exact use case I created `beforeSuccess` for, but it happened before we had `performMutation` available. After that, I've never used it again. Maybe we should deprecate `beforeSuccess` and recommend using `performMutation` anytime you need more fancy actions.

What do you guys think?

**Comment by zkdiff** [comment]
It does seem like `beforeSuccess` overlaps with `performMutation` but the latter provides more flexibility for sure. Would you also deprecate `beforeAction`? That would leave `formAction` for the "happy/simple path" and then if you need either an early response or need to do more fancy stuff, you can use `performMutation` directly.
