### ISSUE TITLE
Transforms are not being applied on server side

### ISSUE THREAD

**Issue by wladiston** [SeasonedSoftware/remix-forms#24]
Curiously transforms are not working on server site. I can see on the request payload that transforms are working fine on client side but when it gets to the serve they are ignored. I don't see why we want to have transforms on the client though. If I just transform a string to number on the client side, it should throw an error on the server since the validation would need a string instead of a number.

**Comment by danielweinmann** [comment]
Hey, @wladiston!

I just ran a test with your code and it seems to be working for me. Let me check if I understand the idea: if I type `1234,56` on the field, `values` inside your mutation should be `{ values: 123456 }`? That's what I'm getting.

**Comment by wladiston** [comment]
Correct, yeap, I actually forgot to close this cause I got it working
