### ISSUE TITLE
How to use the "register" hook with a nested component?

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [SeasonedSoftware/remix-forms#27]
I am using Remix Forms with Mantine components. I have to use the Mantine rich text editor and that cannot be server rendered. So in order to render it in client, I have a wrapper around it so it only renders when it is in the browser.

Since it is the wrapper I will be using, `...register(descriptio)` does not bind it properly to the control. Although rich text editor is not a simple HTML component, I would want to know how to integrate validations with those type of elements.

I know I am missing something obvious, any help is appreciated. Thanks

richtexteditor.tsx
```tsx
import type { RichTextEditorProps } from "@mantine/rte";

export function RichText(props: RichTextEditorProps) {
  if (typeof window !== "undefined") {
    // eslint-disable-next-line import/extensions, global-require
    const { RichTextEditor } = require("@mantine/rte");
    return (
      <RichTextEditor
        controls={[
          ["bold", "italic", "underline", "link"],
          ["unorderedList", "h1", "h2", "h3"],
          ["sup", "sub"],
          ["alignLeft", "alignCenter", "alignRight"],
        ]}
        {...props}
      />
    );
  }

  // Render anything as fallback on server, e.g. loader or html content without editor
  return null;
}
```

usage in page.tsx inside remix form
```tsx
<Field name="description" className="mt-5 mb-1">
  {({ Errors }) => (
    <>
      <RichText
        onChange={(event: any) => {}}
        value={description}
        placeholder=""
        className="mt-1 mb-1"
        classNames={{
          root: "min-h-[200px] border-gray-300",
        }}
      />
      <Errors className="mt-1 text-xs font-semibold text-red-500" />
    </>
  )}
</Field>
```

**Comment by danielweinmann** [comment]
Hey, @VigneshVaidyanathan! I never used Mantine, but it looks like you need to pass the `register` props to your `RichText` component and then pass them along to Mantine's `RichTextEditor`. Working with react-hook-form's [Controller](https://react-hook-form.com/api/usecontroller/controller) will help.

Also, make sure you [forward the ref](https://reactjs.org/docs/forwarding-refs.html) along if you'd like to retain the focus management functionalities.

PS: take a look at remix-utils [ClientOnly](https://github.com/sergiodxa/remix-utils#clientonly) component. It will help you avoid checking for the existence of `window` inside your components.

**Comment by danielweinmann** [comment]
Closing the issue but feel free to reopen it if you need additional help.
