### ISSUE TITLE
Feature: missing types for coercion

### ISSUE THREAD

**Issue by wladiston** [SeasonedSoftware/remix-forms#31]
THIS IS MORE A DISCUSSION THAN PROPERLY AN ISSUE. 

I'm kinda implementing the `formAction` for my remix app and came across with the following situation.

Our form is quite complicated with few dynamic pieces and with some transformations to make the data more appropriate for Prisma and other libraries.
<img width="341" alt="Screen Shot 2022-06-03 at 7 12 15 PM" src="https://user-images.githubusercontent.com/1843792/171961000-9e34cb32-c6ec-4ab4-ade0-4cae3cbe2b95.png">

In this particular form, we have a couple of reusable schemas and some really complex ones...
As an example:
```ts
export const DaytimeRangeSchema = z.preprocess(
  // The field are setting their own index to be able to use the validation
  // This can cause a empty array to be set as default value
  // So we set empty indexes to undefined to keep their order
  arg => Array.apply(0, (arg as []) ?? []),

  // Validate the array
  TimeRangeSchema.array()
    .default([])
    // remove undefined values on server
    .transform(arg =>
      typeof document === 'undefined' ? arg.filter(a => !!a) : arg,
    )
    // Prisma friendly
    .transform(data => data as Prisma.JsonArray),
)
```

Now, I know this kind of dynamic form is not really "remix way" of doing things but sometimes we'll need to sacrifice the "javascript disabled" in exchange of having a better UX. With that said, coercion should be able to find out what kind of inputs it are dealing with and then coerce it. 

I'm not sure exactly how much of these types are really necessary but I kinda have a feeling that some importants are left behind.

Those are the following types I managed to get:
- [ ] ZodAny
- [ ] ZodArray
- [ ] ZodBigInt
- [x] ZodBoolean
- [x] ZodDate
- [ ] ZodDefault
- [ ] ZodDiscriminatedUnion
- [ ] ZodDiscriminatedUnionOption
- [ ] ZodEffects
- [x] ZodEnum
- [ ] ZodFunction
- [ ] ZodIntersection
- [ ] ZodLazy
- [ ] ZodLiteral
- [ ] ZodMap
- [ ] ZodNaN
- [ ] ZodNativeEnum
- [ ] ZodNever
- [ ] ZodNonEmptyArray
- [ ] ZodNull
- [ ] ZodNullable
- [x] ZodNumber
- [ ] ZodObject
- [ ] ZodOptional
- [ ] ZodPromise
- [ ] ZodRawShape
- [ ] ZodRecord
- [ ] ZodSet
- [x] ZodString
- [ ] ZodTuple
- [ ] ZodTupleItems
- [ ] ZodUndefined
- [ ] ZodUnion
- [ ] ZodUnknown
- [ ] ZodVoid

**Comment by diogob** [comment]
I'm closing this since we can still discuss and use it as reference and it does not need to be on our TODO. Thanks for creating the inventory above @wladiston
