### ISSUE TITLE
`successPath` based on an item created in the mutation

### ISSUE THREAD

**Issue by ScottAgirs** [SeasonedSoftware/remix-forms#34]
# Question ~B~
Similarly on the `schema` - I need to provide the enums/options to the user based on the DB entries:

```js
const schema = z.object({
  productCategory: z.enum(["food", "soft-drink", "cosmetics", "other"]), // -- how to get these from the DB? 🤔
  // ...
});
```

~Fingers crossed I haven't missed something super obvious, haha 🤞🏼~ (guess I did miss the `performMutation` example for my Question A 😅)

<details>
Hey folks!

Was great meeting y'all in Remix Conf + so far loving the npm/Remix Form 🥳

# Question A
How can I define a dynamic `successPath` based on some value in the mutation.

Here are the relevant parts:
```js
const mutation = makeDomainFunction(schema)(
  async (values) => {
    const createdItem = await createItem({
      name: "Will it Hurt Me?",
      brandName: "Silky Smooth",
    })

    return createdItem;
  }
);
```

and the `action`:
```js
export const action: ActionFunction = async ({ request }) => {
  return formAction({
    request,
    schema,
    mutation,
    successPath: "/", // ---- this is where I would like to be able to use for example createdItem.slug (which I wouldn't pass from the form, but rather generate on the server)
  });
}
```
</details>

**Comment by danielweinmann** [comment]
Hey, @ScottAgirs! How's it going, man?

About Question A, its actually WTFM Fest 2022 :D we already [accept a function](https://github.com/SeasonedSoftware/remix-forms/blob/main/src/formAction.server.ts#L37) on `successPath` for just that ([here's the implementation](https://github.com/SeasonedSoftware/remix-forms/blob/main/src/formAction.server.ts#L104)). But we still need to have an API Docs section on our website for comprehensive documentation.

About Question B, I don't think you should try to use an enum for data that comes from the database. What I do in similar cases is to load the data inside my loader and pass the `options` prop to either the [form](https://remix-forms.seasoned.cc/examples/forms/labels-and-options) or the [field](https://remix-forms.seasoned.cc/examples/forms/form-with-children).

How does that sound?

**Comment by ScottAgirs** [comment]
> Hey, @ScottAgirs! How's it going, man?
> 
> About Question A, its actually WTFM Fest 2022 :D we already [accept a function](https://github.com/SeasonedSoftware/remix-forms/blob/main/src/formAction.server.ts#L37) on `successPath` for just that ([here's the implementation](https://github.com/SeasonedSoftware/remix-forms/blob/main/src/formAction.server.ts#L104)). But we still need to have an API Docs section on our website for comprehensive documentation.
> 
> About Question B, I don't think you should try to use an enum for data that comes from the database. What I do in similar cases is to load the data inside my loader and pass the `options` prop to either the [form](https://remix-forms.seasoned.cc/examples/forms/labels-and-options) or the [field](https://remix-forms.seasoned.cc/examples/forms/form-with-children).
> 
> How does that sound?

Thanks for asking, going great, new weekend project - @will-it-hurt-me!! 🤩 😅

Both solutions work great for my current use-case! :) Especially your `Question B` answer - totally blanked on this :)

Thanks again 🙌🏼
