### ISSUE TITLE
Feature: custom input registration

### ISSUE THREAD

**Issue by wladiston** [SeasonedSoftware/remix-forms#35]
I think we could improve the DX a bit just by exporting the registered input already as a prop.

Currently if we want to make a custom input we need to do this:
```tsx
<Field name="email">
  {({ Label, Errors }) => (
    <>
      <Label />
      <input
        type="email"
        {...register('email')}
        className="border-2 border-dashed rounded-md"
      />
      <Errors />
    </>
  )}
</Field>
```

Since the Field has the name it would make sense to just do this
```tsx
<Field name="email">
  {({ Label, Errors, props }) => (
    <>
      <Label />
      <input type="email"  {...props}  className="border-2 border-dashed rounded-md" />
      <Errors />
    </>
  )}
</Field>
```

**Comment by danielweinmann** [comment]
Hey, @wladiston! That's a great idea and I agree with your suggested API :D thanks!

Would you like to send a PR with this?

**Comment by wladiston** [comment]
Probably not... I'm doing some tests with that build-in registration and I'm running into some trouble.

I have this scenario where I'm usiing a 3rd party phone number input that masks the user input with the correct country format. This component only exposes controllable props. It only works well with the defaultValues and etc, if I let the component Controller from react-hook-form handles the registration and render for me.

```tsx
import { useForm, Controller } from "react-hook-form";
import PhoneInput, { isValidPhoneNumber } from "react-phone-number-input";
....
        <Controller
          name="phone-input"
          control={control}
          rules={{
            validate: (value) => isValidPhoneNumber(value)
          }}
          render={({ field: { onChange, value } }) => (
            <PhoneInput
              value={value}
              onChange={onChange}
              defaultCountry="TH"
              id="phone-input"
            />
          )}
        />
```

**Comment by halindraprakoso** [comment]
I'm still struggling with this. I'm using primereact controlled component and the `dateStart` value is always null. Am I missing something?
```js
...
 {({ Field, Button, Errors, control }) => (
          <>
            <Field name="dateStart">
              {({ Label, Errors }) => (
                <>
                  <Label />
                  <Controller
                    name="dateStart"
                    control={control}
                    render={({ field }) => (
                      <Calendar
                        id={field.name}
                        value={field.value}
                        onChange={(e) => field.onChange(e.value)}
                      />
                    )}
                  />
                  <Errors />
                </>
              )}
            </Field>
...
```

**Comment by samjohnduke** [comment]
@halindraprakoso - I too am facing similar issues - Did you have any luck finding a solution.

**Comment by samjohnduke** [comment]
Note - For those who see the above and a wondering whats going on. When using Controller, if the `render` of the controller doesn't put a hidden or otherwise input into the dom, this won't work. So its a matter of adding 
```
<Controller
  name="dateStart"
  control={control}
  render={({ field }) => (
    <>
     <input name={field.name} value={field.value} type="hidden" />
      <Calendar
        id={field.name}
        value={field.value}
         onChange={(e) => field.onChange(e.value)}
       />
    <>
  )}
/>
```

Hope this helps

**Comment by danielweinmann** [comment]
I'm closing this issue because - at least for now - we don't want to increase our API with helpers for custom components when react-hook-form already has a great API for that.
