### ISSUE TITLE
Support for custom schema validators

### ISSUE THREAD

**Issue by marcus-sa** [SeasonedSoftware/remix-forms#36]
Have you considered allowing developers to use custom schema validators?
I'd much rather use https://deepkit.io/library/type instead of https://zod.dev

**Comment by gustavoguichard** [comment]
Hey @marcus-sa !
Thank you for submitting the issue, sorry for closing it out prior to commenting, I'm testing this feature on my mobile's github app 😅

That said we don't plan to support custom serializers in the foreseeable feature - which may be the next major release.

It doesn't seem to be too hard to do it so we will keep an eye on "Type" and this sort of request tho.

Is there any specific reason you'd use one over another? Do you have any API suggestions?

Cheers
