### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by moishinetzer** [SeasonedSoftware/remix-forms#40]
I have noticed that just setting the value prop e.g. `value="myDefaultValue"` yields VERY odd results especially when routing to another route with the same form, sometimes the value is not changed to the new default value.

**To clarify, my use case is the following.**

After submit I redirect to the /new page which is essentially the form however the `<Outlet />` renders it with the default value set as `value=""`, in this specific situation the form is not cleared.

The same happens when moving from route to route within the same <Outlet /> when it tries to render the form with value="" i.e. trying to clear it.

**Comment by moishinetzer** [comment]
I'm sorry I did not clarify, however the above pr does not solve my scenario, as I was not clear enough with the specific use case.

I have updated my original question accordingly.

**Comment by moishinetzer** [comment]
```ts
<Form
  schema={imageCategorySchema}
  className="border-b p-8"
  onTransition={({ transition, setFocus, reset, formState }) => {
    const { isDirty } = formState;
    if (transition.submission && isDirty) {
      setFocus("name");
      reset();
    }
  }}
/>
```

It seems as though adding the onTransition prop with the following seems to work however surely the default behaviour should be resetting onSubmit anyways?

**Comment by moishinetzer** [comment]
Any help on this?

**Comment by gustavoguichard** [comment]
Hey @moishinetzer ! Sorry for taking so long, we are in the process of bringing the docs to this repo and improving the overall DX of both the Docs and the library. We are about to finish those tasks and will get back to the issues and PRs soon ;)

**Comment by diogob** [comment]
@moishinetzer I do believe #98 should fix this. We will ship this PR next week
