### ISSUE TITLE
Unable to make checkbox required

### ISSUE THREAD

**Issue by jnoahjohnson** [SeasonedSoftware/remix-forms#42]
I am trying to make a checkbox required to be true within the zod schema, but the form is still submitting no matter what I have tried so far. There is an example that shows this on the website, but it just sets the default to false. It has a required indicator, but accepts either true or false.

Is there a way to do this currently?

**Comment by LandSprutte** [comment]
if you want to make a "Terms of Service" kinda check:

`
tos: z.custom((data) => data === true, {
    message: "You have to accepts terms of service",
  }),
`

and then make a custom field in your form for the "tos"-field :)

**Comment by jnoahjohnson** [comment]
Thank you!

**Comment by jnoahjohnson** [comment]
@LandSprutte  Okay, so I am actually running into an issue with this. It looks like when I create a custom input then the data is coming through as just empty strings. Any idea on this?

<img width="1001" alt="Screen Shot 2022-06-29 at 8 00 08 PM" src="https://user-images.githubusercontent.com/
<img width="284" alt="Screen Shot 2022-06-29 at 8 00 17 PM" src="https://user-images.githubusercontent.com/6829286/176576609-0ce6e19f-5a0d-4241-af99-2ffaec978013.png">
6829286/176576585-c4606489-6600-4ee9-8c05-48ebe7199fe6.png">

**Comment by LandSprutte** [comment]
@jnoahjohnson try:

```ts
  tos: z.custom((data) => data, {
    message: "must accept TOS",
  }),

...... // other stuff

<Field name="agree-1" fieldType="boolean" type="checkbox" ....>
...
</Field>
```

**Comment by mauscoelho** [comment]
Like this, you don't need to customise the Field
```
privacy: z.boolean().refine(value => value === true, { message: 'You must agree to the privacy statement' })
```
