### ISSUE TITLE
Errors not shown with zod refine

### ISSUE THREAD

**Issue by mahrz24** [SeasonedSoftware/remix-forms#47]
I have a schema with a refinement:

```
const schema = z.object({
    email: z.string().min(1).email(),
    password: z.string().min(1),
    passwordConfirmation: z.string().min(1)
}).refine((data) => data.password === data.passwordConfirmation, {
    message: 'Passwords do not match',
    path: ['passwordConfirmation'],
})
```

I would have expected this to work with remix-forms, ideally with the error either being global or attached to the field belonging to the path. However it is not working. I see a typescript error when passing the schema:

```
Type 'ZodEffects<ZodObject<{ email: ZodString; password: ZodString; passwordConfirmation: ZodString; }, "strip", ZodTypeAny, { email: string; password: string; passwordConfirmation: string; }, { ...; }>, { ...; }, { ...; }>' is missing the following properties from type 'ZodObject<ZodRawShape, UnknownKeysParam, ZodTypeAny, any, any>': _shape, _unknownKeys, _catchall, _cached, and 16 more.
```

During runtime, the validation somehow works (if I print during the refine step, I can see that the validation is executed) and the form is submitted. However, validation errors are not shown and I do not get any runtime error / exception (in the browser or on the server side).

**Comment by zolzaya** [comment]
I have a same issue. Did you solve it?

**Comment by gustavoguichard** [comment]
@mahrz24 and @zolzaya  when you use Zod's `.refine` on a schema it is not a Schema anymore, it will become `z.ZodEffects`.
The remix-forms' `Form` element should receive a `schema` though.

The solution is to save the schema in a `const` and refine it only in the domain function like so:

```ts
// Your schema file
const schema = z.object({
    email: z.string().min(1).email(),
    password: z.string().min(1),
    passwordConfirmation: z.string().min(1)
})

// Your component
const MyComponent = () => {
  return <Form schema={schema} />
}

// Your domain file
const df = makeDomainFunction(
  schema.refine((data) => data.password === data.passwordConfirmation, {
    message: 'Passwords do not match',
    path: ['passwordConfirmation'],
  })
)(async ({ email, password, passwordConfirmation }) => {
  // ...
})
```

This solution should make the Form work on both client and server.

I'll be closing this issue for now, feel free to reopen it if my solution doesn't suffice ;) .

**Comment by zolzaya** [comment]
@gustavoguichard cool thanks :)
