### ISSUE TITLE
About lodash

### ISSUE THREAD

**Issue by tavoyne** [SeasonedSoftware/remix-forms#62]
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/29731597/181220128-0981b9e5-443b-4f2d-b403-087a55c5a9d5.png">

`remix-form` is only importing `concat` and `startCase` from `lodash`, but depends on the whole package, which is not tree-shakeable. What about switching to [`lodash-es`](https://www.npmjs.com/package/lodash-es) or to individual packages (e.g. [`lodash.concat`](https://www.npmjs.com/package/lodash.concat))? OR... moving away from lodash?

Can do a PR.

**Comment by gustavoguichard** [comment]
Hey @tavoyne , thanks for pointing this out!
I was going to make a little test and ended up creating a PR. Check #63 out ;)

**Comment by gustavoguichard** [comment]
Hey @tavoyne I just published an RC to test the removal of lodash and I'm super happy about the results.

We really appreciate your time and contributions on this one 🥳 

## Before 😱 
![Captura de Tela 2022-07-27 às 11 00 39](https://user-images.githubusercontent.com/566971/181280074-de18e0db-107c-4e9d-bf78-a468a232b48d.png)

## After 😌 
![Captura de Tela 2022-07-27 às 11 55 22](https://user-images.githubusercontent.com/566971/181280100-178186e7-09bf-4629-8cb2-44625ad09f98.png)

**Comment by tavoyne** [comment]
That's something 🥹

Happy to help!

Why not making `react-hook-form` a peer dependency while we're at it?

**Comment by gustavoguichard** [comment]
Agree, now that we have a monorepo it'll be easier to do it.
I'm probably not going to be doing it today.
Feel free to either create another issue or even a PR ;D

Cheers

**Comment by gustavoguichard** [comment]
@tavoyne I couldn't help but try your suggestion just to see the results:
![Captura de Tela 2022-07-27 às 14 28 17](https://user-images.githubusercontent.com/566971/181312673-8ecddb78-0d20-47cd-bd06-e986d9cd8b5d.png)

Will be publishing soon
