### ISSUE TITLE
need example on using controlled components.

### ISSUE THREAD

**Issue by halindraprakoso** [SeasonedSoftware/remix-forms#70]
hello, I have been enjoying remix-forms. However I need to use some of primereact components which were controlled only and I can't seem to make it work; which is a blocker. 
I've tried using the `Controller` component:
```js
...
 {({ Field, Button, Errors, control }) => (
          <>
            <Field name="costCenter">
              {({ Label, Errors }) => (
                <>
                  <Label />
                  <Controller
                    name="costCenter"
                    control={control}
                    render={({ field }) => (
                      <Dropdown
                        {...field}
                        id={field.name}
                        onChange={(e) => field.onChange(e.value)}
                        options={options}
                      />
                    )}
                  />
                  <Errors />
                </>
              )}
            </Field>
...
```
, as well as `setValue` and `watch` combo. Unfortunately, both approaches were submitting an empty string even though the values got rendered just fine. I hope I'm just missing something, since I haven't used react-hook-form before.

**Comment by danielweinmann** [comment]
Hey, @halindraprakoso! Does your `Dropdown` component render am html input or select? If so, does it render the `value` attribute correctly?

Sometimes controlled components only use internal state to store the values or don't render proper html form input. When that's the case, you need to add a hidden input with the result of `watch('myField')` in order for it to be sent to the server.

**Comment by halindraprakoso** [comment]
Hi @danielweinmann 
I forgot about using hidden input 😅 I guess I was too trigger-happy with all the generated inputs. Anyway, the component does render html input. However on quick glance, the props doesn't seem to be passed on to the input. It worked fine with hidden inputs though. thank you!

**Comment by danielweinmann** [comment]
Yeah, when it comes to custom inputs, we try to do less magic and give you more control. Unfortunately, that means more work when your base components are not following web standards. I'm glad you were able to solve it!
