### ISSUE TITLE
Example forms are not accessible

### ISSUE THREAD

**Issue by janhesters** [SeasonedSoftware/remix-forms#72]
## Description

The screenreader frequently omits the labels (text field as opposed to textfield with label email) and rarely reads out the errors that describe the fields. In fact, if the auto focus shifts back to the field, it just reads the value and not the current error.

Check out [this Loom recording](https://www.loom.com/share/4fafef2321b44e28b6087a6b5a54d033) to see the errors happening.

All forms behaved like this so this library likely doesn't put out accessible forms 😕 Or I'm just a noob at using screen readers 😄 

## How To Reproduce

Try using the form with a screen reader without getting lost (close your eyes if you can see) by:

1. Navigate to https://remix-forms.seasoned.cc/examples/actions/field-error.
1. Opening Safari,
1. Turning on Voice Over (`cmd + f5`)
1. Navigating to the email field.
1. Typing in an invalid email.
1. Navigating to the password field.
1. Leaving the password field blank.
1. Navigating to OK and hitting enter.

## Likely cause:

The generated HTML labels the div around the error as `id=errors-for-email` as opposed to the element that contains the error.

![Screenshot 2022-08-04 at 17 03 34](https://user-images.githubusercontent.com/31096420/182881000-f67ec781-cfce-41bc-8b8c-8737a205a6dd.png)

**Comment by gustavoguichard** [comment]
Hey @janhesters , I'm no expert in a11y or screen readers, but when I replicate the steps you've done I hear the message. 
You have to wait at least 2s after she stops talking though... first she introduces the place you are at: "Email field, required, invalid data", then after couple seconds it says: "Invalid email".

This is the result of the generated HTML, the id of the error message must be unique (as in all IDs must be unique) that error id is used in conjunction with `aria-invalid` and `aria-describedby` though, that's how it informs the screen reader:
![Captura_de_Tela_2022-08-04_às_16_08_58](https://user-images.githubusercontent.com/566971/182934305-62569593-a845-415d-87d8-98acc7aa97a6.jpg)

I'd like to have a specialist opinion here, but I don't think there's an actual a11y issue from what I can tell.

**Comment by janhesters** [comment]
@gustavoguichard Maybe I'm doing something wrong. I did it again and recorded a Loom [here](https://www.loom.com/share/7eb63e7a1f7e4fdebc6993734f6ad1db). Same result as in the issue I filed. I made sure to wait two seconds to see if anything comes up.

**Comment by gustavoguichard** [comment]
Weird... I'm far from a specialist in the subject, what I (think I) know is how to use those `aria` attributes and that it works with my Mac VoiceOver.

I'd love if someone with better expertise would see this issue and help us out here!

**Comment by diogob** [comment]
@gustavoguichard @janhesters I understand the state of affairs with screen readers is far from ideal. I've done some tests with Firefox and had very little success. Using the [Screen Reader](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn) on Chrome I had a better experience and could hear the errors, even if they sound a bit awkward.

I'm closing this since it seems the library is rendering the proper aria attributes and keeping proper references to the error descriptions.
