### ISSUE TITLE
Run dev on host 0.0.0.0

### ISSUE THREAD

**Issue by C0mput3r5c13nt15t** [SeasonedSoftware/remix-forms#75]
Hi there,

me again ... Since I am working with Vagrant I need the application to run on 0.0.0.0 to be able to access it easily from my host but neither the usual flags (-H and --host) nor the HOST="0.0.0.0" in the .env seemed to resolve the issue. In the documentation I couldn't find anything either and the answer from Discord didn't work.

Hope you can help me <3

**Comment by gustavoguichard** [comment]
Hey @C0mput3r5c13nt15t , nice to hear from you again.
I don't think this is an issue with remix-forms, the only server in this monorepo is a basic Remix application at `./apps/web` and it is a remix/netlify app.
I encourage you to play with either the [HOST environment var](https://github.com/remix-run/remix/blob/d09663e608cc5373a25f1c23ec32844ff67ad9a6/packages/remix-serve/cli.ts) for Remix or the [`netlify.toml`](https://github.com/SeasonedSoftware/remix-forms/blob/main/apps/web/netlify.toml).

I'm going to close this issue for now, feel free to reopen it if you think there's a problem with remix-forms itself ;)
