### ISSUE TITLE
Idea: Improve user experience with specialized input type or input mode

### ISSUE THREAD

**Issue by armandabric** [SeasonedSoftware/remix-forms#76]
Hi there! 

I have started to use `remix-form` and one thing I notice is that an input generated from a schema enforcing a number will generate a generic text input:

```ts

const schema = z.object({ foo: z.number() });

// Will generate something like:
// <input type="text" ... />
```

To improve the user experience, it should be generated as a number input: `<input type="number" ... />`. It allow to type only number, and number related character, this help the user. But the number input is not fancy: it shows arrow that it generally considered in an issue by a lot of designer. There no widely implemented way to remove/hide them. 

Another improvement could be to add the `inputmode="decimal"` on the field the current textual field. It sill only help the mobile, but that's already a win.

### Use cases

```ts
// Number
const schema = z.object({ foo: z.number() });
const schema = z.object({ foo: z.number().step(2) }); // <input type="number" step="2" ... />
const schema = z.object({ foo: z.number().min(1) }); // <input type="number" min="1" ... />
const schema = z.object({ foo: z.number().max(5) }); // <input type="number" max="5" ... />
const schema = z.object({ foo: z.number().positive() }); // <input type="number" min="0" ... />

// Email
const schema = z.object({ z.string().email() }); // <input type="email" ... />


// Url
const schema = z.object({ z.string().url() }); // <input type="url" ... />
```

:link: https://developer.mozilla.org/fr/docs/Web/HTML/Global_attributes/inputmode
:link: https://developer.mozilla.org/fr/docs/Web/HTML/Element/input#les_diff%C3%A9rents_types_de_champs_input

**Comment by danielweinmann** [comment]
Hey, @armandabric! Thanks for creating the issue. We don't want to enforce this pattern, but we'd love to make it easy for people to adopt it. I created #83 with an idea for a better solution for this.

Right now, if you want to achieve this goal you can do it using `renderField` and introspecting the `shape` prop, like I suggested on #81.

I'm closing this issue for now, in favor of #83, but feel free to reopen it at any time.
