### ISSUE TITLE
Customize Textarea (rows attribute)

### ISSUE THREAD

**Issue by jjanyan** [SeasonedSoftware/remix-forms#79]
Sorry to reach out so soon again. 

How would I override the number of rows for a textarea? I can't find any examples of it not hardcoded to 5.

e.g.

```
<textarea rows="15"></textarea>
```

**Comment by danielweinmann** [comment]
Hey, @jjanyan! The more issues you create, the more you contribute to the community! Don't sweat 😄

You can create your own component and pass it to the `multilineComponent` prop. You can do that generically, passing it in your project's `Form` component, or locally, passing this prop to the specific form you want to have a different number of rows. Here's an example of a [text area component](https://github.com/SeasonedSoftware/remix-forms/blob/main/apps/web/app/ui/text-area.tsx).

In case you already have a multiline component and don't want to create a component for each form you render, you can pass children to `Field`, access the `Multiline` component, and pass the `rows` prop to it. Something like this:

```tsx
const schema = z.object({
  name: z.string().nonempty(),
  bio: z.string().nonempty(),
})

export default () => (
  <Form schema={schema}>
    {({ Field, Errors, Button }) => (
      <>
        <Field name="name" />
        <Field name="bio">
          {({ Label, Multiline, Errors }) => (
            <>
              <Label />
              <Multiline rows={12} />
              <Errors />
            </>
          )}
        </Field>
        <Errors />
        <Button />
      </>
    )}
  </Form>
)
```

I'm closing the issue for now but feel free to reopen it at any time!
