### ISSUE TITLE
How to make a field required (in a browser-recognized way)?

### ISSUE THREAD

**Issue by fritzblue** [SeasonedSoftware/remix-forms#80]
Something being required on the zod schema alone does not seem to produce the `required` property on the generated input field.

What is the best way to do this? Digging all the way down to the input field just to add the property feels like overkill.

**Comment by danielweinmann** [comment]
We don't want to enforce this pattern on people, but you can achieve this using the `renderField` prop on your project-wide [custom Form component](https://remix-forms.seasoned.cc/get-started):

import type { FormProps } from 'remix-forms'
import { Form as RemixForm } from 'remix-forms'
import type { SomeZodObject } from 'zod'

export default function Form<Schema extends SomeZodObject>(
  props: FormProps<Schema>,
) {
  return (
    <RemixForm<Schema>
      // All your other customizations would go here
      renderField={({ Field, required, ...props }) => {
        return (
          <Field required={required} {...props}>
            {({ Label, Input, Errors }) => (
              <>
                <Label />
                <Input required={required} />
                <Errors />
              </>
            )}
          </Field>
        )
      }}
      {...props}
    />
  )
}

IMPORTANT: this example is a simplification that would make all your forms render only inputs. Selects, checkboxes, etc, would be overridden. I created #84 to allow for an easier way to achieve your goal. But for now, you can introspect the props passed to `renderField` (like `shape`, for instance) and make your `renderField` function smarter.

**Comment by danielweinmann** [comment]
I'm closing this issue for now, but feel free to reopen it at any time.

**Comment by fritzblue** [comment]
Appreciate the thoughtful responses, looking forward to see how the proposed updates pan out.
