### ISSUE TITLE
Pass extra data to the mutation that's not coming from the form submission

### ISSUE THREAD

**Issue by netdesignr** [SeasonedSoftware/remix-forms#88]
Hi,

Is there any way we can pass some extra data to the mutation, data that's not coming from the form? I wonder if the `beforeAction` callback might be a good use here but I'm not entirely sure how that would work.
Basically, alongside the data submitted from the form I want to pass some other value that won't be available before the form submission but it's important the mutation has it before the final call, if that makes sense?

Thanks a lot!

**Comment by gustavoguichard** [comment]
Hey @netdesignr ! 
Where does your data come from? Wouldn't it make sense to put it on your [environment](https://github.com/SeasonedSoftware/domain-functions#taking-parameters-that-are-not-user-input)?

**Comment by netdesignr** [comment]
Hi @gustavoguichard,
To give some more context

```
const session = await stripe.checkout.sessions.create({});

await formAction({
    request,
    schema,
    mutation,
}).then((resp) => resp.json());

```
Inside the mutation there's a function data adds the data to the DB. I need to be able to pass the `session` to the DB too.

Thanks a lot for the quick reply on this matter.

**Comment by gustavoguichard** [comment]
Cool @netdesignr , I think the session is the perfect example of the environment feature of domain-functions.
LMK if it works for you

**Comment by netdesignr** [comment]
@gustavoguichard that solved my problem.

When you mentioned about environment on first reply I didn't realise that you actually linked to the actual doc and I thought you were talking about `.env`. 

Thank you!
