### ISSUE TITLE
mandatory Select without default value?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [SeasonedSoftware/remix-forms#97]
How to do it without custom component?

https://remix-forms.seasoned.cc/examples/schemas/enums

**Comment by xiaoyu-tamu** [comment]
workaround
```ts
const schema = z.object({
  enum: z
    .enum(['A','B','C'])
    .nullable()
    .refine((value) => typeof value === 'string', 'required'),
});

```

**Comment by gustavoguichard** [comment]
That is a good solution indeed @xiaoyu-tamu . Probably what I'd have done.
I'm going to close this issue as this solution seems to suffice for auto generated forms.

**Comment by danielweinmann** [comment]
Actually, and unintentionally, #98 will make this the default behavior @xiaoyu-tamu and @gustavoguichard :D 

I'm going to reopen the issue so we close it only when this is released.

**Comment by diogob** [comment]
[1.1.0 released](https://github.com/SeasonedSoftware/remix-forms/releases/tag/1.1.0). This is the default behaviour now.
