### ISSUE TITLE
Frontend agnostic, way to use remix-forms with Chakra instead of Tailwind?

### ISSUE THREAD

**Issue by Jarrodsz** [SeasonedSoftware/remix-forms#99]
This library seems really promising but tailwind is heavily integrated inside the whole frontend.

If I were to use it with Chakra instead of Tailwind I would have to rewrite all the components. 
Or
Is there "chakra compatible port" of this available and documented somewhere?

Im fairly new to remix and react so forgive this newbie questions. 

I really do like tailwind but after investigating frontend rendering it seems like Chakra is a bit more clean using just components. 
Especially the many tailwind classes ( which give flexibility ) have been throwing me off a bit after building a few marketing sites with it. It take a lof of time debugging tailwind classes to make it compatible for all viewports ( mobile, tablets, desktop ).

**Comment by diogob** [comment]
Hi @Jarrodsz , remix-forms is not tied to Tailwind, it's just the library we chose for the website, hence it's in the repository as an example and for our testing purposes. The only runtime dependencies (as of today) are:

```
"domain-functions": ">=1.0.0",
"react": ">=16.8",
"react-hook-form": ">=7.27",
"zod": ">=3.12"
```
Take a look at the [form.tsx file in the example app](https://github.com/SeasonedSoftware/remix-forms/blob/main/apps/web/app/ui/form.tsx#L27) and you can use that as a template to customize components on your project using Chakra.

**Comment by danielweinmann** [comment]
@Jarrodsz, I just created a quick example of how to integrate Remix Forms and Chakra UI: https://github.com/SeasonedSoftware/remix-forms-chakra-ui-example
